name: DEPLOYMENT CLI

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
          with:
            heroku_api_key: ${{ secrets.HEROKU_APIKEY }}
            heroku_app_name: ${{ secrets.HEROKU_APPNAME }}
            heroku_email: franna.jaya@gmail.com